version:  '3.7'
services:
  app:
    image: php:8.1-apache
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - "80:80"
  composer:
    image: composer:2.1
    volumes:
      - ./:/app
    working_dir: /app
    command: install